### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Fix the markup, and elaborate on why locally merge the release branch into `dev`

### CODE REVIEW

**Review by smartie2076 — APPROVED** [review]

**Comment by SabineHaas** [comment]
I have a small comment about the branch naming: To my mind, the branch name does not necessarily have to include or start with `feature/` but could for example start with `fix/` if you are just fixing an error, etc. - what do you think?

**Comment by jnnr** [comment]
Looks good!
A comment on the part that is not affected by this PR: In oemof, we have the convention to separate words with - instead of _

And a remark: There is a typo in 'versionning'.

**Review by jnnr — APPROVED** [review]

**Comment by Bachibouzouk** [comment]
> A comment on the part that is not affected by this PR: In oemof, we have the convention to separate words with - instead of _

thanks for your comment, you mean for branch names?

**Comment by Bachibouzouk** [comment]
> - what do you think?

it was implicit :), maybe I'll write it explicitly

**Comment by jnnr** [comment]
> thanks for your comment, you mean for branch names?

Yes, exactly.

**Pull request merged**
